import type { SurveyPanel } from './types.ts'

/**
 * Catalog of platforms that pay for surveys, studies and microtasks.
 *
 * ## About the numbers
 *
 * `typicalUnitsPerSurvey`, `typicalMinutes` and especially `screenOutRate` are
 * calibration estimates, not figures published by these platforms. No panel
 * discloses its screen-out rate, because it is the number that would tell you
 * how bad the hourly rate really is. They are set from the general shape of
 * each platform — a prescreened research marketplace screens out far less than
 * an open survey router — and they drive every ranking this tool produces.
 *
 * Treat them as a starting point and tune them against your own results. Two
 * people with different demographics genuinely earn different rates on the same
 * panel, so a catalog that claimed precision here would be lying.
 *
 * Conversion rates and cash-out minimums do change. Verify before committing
 * hours to any one platform.
 */
export const DATA_VINTAGE = '2026-07'

export const PANELS: SurveyPanel[] = [
  // ------------------------------------------------- paid research studies
  {
    id: 'prolific',
    name: 'Prolific',
    kind: 'research-study',
    url: 'https://www.prolific.com/',
    payoutUnit: 'usd',
    unitsPerDollar: 1,
    typicalUnitsPerSurvey: 2.5,
    typicalMinutes: 15,
    // Studies are targeted from your profile, so you mostly qualify for what
    // you are shown. This is the whole reason it outperforms survey routers.
    screenOutRate: 0.15,
    screenerMinutes: 2,
    typicalSurveysPerWeek: 10,
    minCashoutUsd: 6.5,
    payoutSpeed: 'days',
    giftCards: ['PayPal', 'Cash'],
    regions: ['US', 'GB', 'CA', 'AU', 'IE', 'EU'],
    inviteOnly: false,
    mobileOnly: false,
    notes:
      'Academic and industry research with a published minimum hourly rate. The best real rate on this list, and the main constraint is supply — fill in every profile question, then check throughout the day, because good studies fill within minutes.',
  },
  {
    id: 'user-interviews',
    name: 'User Interviews',
    kind: 'research-study',
    url: 'https://www.userinterviews.com/',
    discoveryUrls: ['https://www.userinterviews.com/projects'],
    payoutUnit: 'usd',
    unitsPerDollar: 1,
    typicalUnitsPerSurvey: 60,
    typicalMinutes: 45,
    screenOutRate: 0.75,
    screenerMinutes: 5,
    typicalSurveysPerWeek: 0.5,
    minCashoutUsd: 0,
    payoutSpeed: 'days',
    giftCards: ['Amazon', 'Visa', 'PayPal'],
    regions: ['US', 'CA', 'GB'],
    inviteOnly: false,
    mobileOnly: false,
    notes:
      'Individual studies paying $50-150, usually a scheduled video call. You apply and most applications go nowhere, but one accepted study beats a month of survey routers. Apply to everything you plausibly qualify for.',
  },
  {
    id: 'respondent',
    name: 'Respondent',
    kind: 'research-study',
    url: 'https://www.respondent.io/',
    payoutUnit: 'usd',
    unitsPerDollar: 1,
    typicalUnitsPerSurvey: 120,
    typicalMinutes: 60,
    screenOutRate: 0.85,
    screenerMinutes: 6,
    typicalSurveysPerWeek: 0.3,
    minCashoutUsd: 0,
    payoutSpeed: 'days',
    giftCards: ['PayPal', 'Cash'],
    regions: ['US', 'GB', 'CA', 'AU'],
    inviteOnly: false,
    mobileOnly: false,
    notes:
      'The highest per-study payouts anywhere, weighted heavily toward B2B and professional roles. If you have a specialised job title this is the single best use of your time; if you do not, expect to be screened out almost every time.',
  },
  {
    id: 'usertesting',
    name: 'UserTesting',
    kind: 'research-study',
    url: 'https://www.usertesting.com/',
    payoutUnit: 'usd',
    unitsPerDollar: 1,
    typicalUnitsPerSurvey: 10,
    typicalMinutes: 20,
    screenOutRate: 0.6,
    screenerMinutes: 4,
    typicalSurveysPerWeek: 2,
    minCashoutUsd: 10,
    payoutSpeed: 'days',
    giftCards: ['PayPal'],
    regions: ['US', 'GB', 'CA', 'AU'],
    inviteOnly: false,
    mobileOnly: false,
    notes:
      'Think-aloud website tests, a flat $10 for about 20 minutes. You must narrate continuously and audibly — quiet recordings get rejected unpaid. Requires a microphone and a screen recorder.',
  },

  // ------------------------------------------------------- invite-screened
  {
    id: 'pinecone',
    name: 'Pinecone Research',
    kind: 'survey-panel',
    url: 'https://www.pineconeresearch.com/',
    payoutUnit: 'points',
    unitsPerDollar: 100,
    typicalUnitsPerSurvey: 300,
    typicalMinutes: 15,
    // They target from your profile before inviting, so screen-outs are rare.
    screenOutRate: 0.1,
    screenerMinutes: 2,
    typicalSurveysPerWeek: 3,
    minCashoutUsd: 3,
    payoutSpeed: 'days',
    giftCards: ['Amazon', 'Walmart', 'Target', 'PayPal'],
    regions: ['US', 'CA', 'GB'],
    inviteOnly: true,
    mobileOnly: false,
    notes:
      'A flat $3 per survey with almost no screening, which makes the hourly rate one of the best here. The catch is entry: recruitment is by invitation through their ads and closes when demographic quotas fill. You cannot simply sign up.',
  },

  // ------------------------------------------------------------- routers
  {
    id: 'swagbucks',
    name: 'Swagbucks',
    kind: 'gpt-router',
    url: 'https://www.swagbucks.com/',
    payoutUnit: 'points',
    unitsPerDollar: 100,
    typicalUnitsPerSurvey: 60,
    typicalMinutes: 15,
    screenOutRate: 0.5,
    screenerMinutes: 4,
    typicalSurveysPerWeek: 25,
    minCashoutUsd: 3,
    payoutSpeed: 'same-day',
    giftCards: ['Amazon', 'Walmart', 'Target', 'Starbucks', 'PayPal'],
    regions: ['US', 'GB', 'CA', 'AU', 'IE'],
    inviteOnly: false,
    mobileOnly: false,
    notes:
      'The biggest router, and the low cash-out is its real advantage — a $3 Amazon card is reachable in a couple of sessions. Survey rates are poor; the shopping portal and daily goal bonuses are where regulars actually earn.',
  },
  {
    id: 'prizerebel',
    name: 'PrizeRebel',
    kind: 'gpt-router',
    url: 'https://www.prizerebel.com/',
    payoutUnit: 'points',
    unitsPerDollar: 100,
    typicalUnitsPerSurvey: 70,
    typicalMinutes: 13,
    screenOutRate: 0.5,
    screenerMinutes: 4,
    typicalSurveysPerWeek: 25,
    minCashoutUsd: 2,
    payoutSpeed: 'instant',
    giftCards: ['Amazon', 'Visa', 'Steam', 'PayPal'],
    regions: ['US', 'GB', 'CA', 'AU', 'WW'],
    inviteOnly: false,
    mobileOnly: false,
    notes:
      'Lowest threshold and fastest redemption of the routers, often instant. Good first platform because you find out quickly whether you get paid at all. Survey supply thins out sharply outside the US and UK.',
  },
  {
    id: 'branded-surveys',
    name: 'Branded Surveys',
    kind: 'survey-panel',
    url: 'https://surveys.gobranded.com/',
    payoutUnit: 'points',
    unitsPerDollar: 100,
    typicalUnitsPerSurvey: 75,
    typicalMinutes: 15,
    screenOutRate: 0.5,
    screenerMinutes: 4,
    typicalSurveysPerWeek: 15,
    minCashoutUsd: 5,
    payoutSpeed: 'days',
    giftCards: ['Amazon', 'Walmart', 'Target', 'PayPal'],
    regions: ['US', 'GB', 'CA'],
    inviteOnly: false,
    mobileOnly: false,
    notes:
      'Straightforward panel with a daily-streak bonus that meaningfully lifts the rate if you show up every day. Points are quoted per survey up front, so you can decline bad ones before starting.',
  },
  {
    id: 'survey-junkie',
    name: 'Survey Junkie',
    kind: 'survey-panel',
    url: 'https://www.surveyjunkie.com/',
    payoutUnit: 'points',
    unitsPerDollar: 100,
    typicalUnitsPerSurvey: 100,
    typicalMinutes: 18,
    screenOutRate: 0.55,
    screenerMinutes: 4,
    typicalSurveysPerWeek: 15,
    minCashoutUsd: 5,
    payoutSpeed: 'days',
    giftCards: ['Amazon', 'Target', 'PayPal'],
    regions: ['US', 'CA', 'AU'],
    inviteOnly: false,
    mobileOnly: false,
    notes:
      'Clean interface and honest length estimates, but a high screen-out rate. Pays a small consolation for disqualifications, which softens the wasted time without fixing it.',
  },
  {
    id: 'inboxdollars',
    name: 'InboxDollars',
    kind: 'gpt-router',
    url: 'https://www.inboxdollars.com/',
    payoutUnit: 'usd',
    unitsPerDollar: 1,
    typicalUnitsPerSurvey: 0.75,
    typicalMinutes: 15,
    screenOutRate: 0.55,
    screenerMinutes: 4,
    typicalSurveysPerWeek: 12,
    minCashoutUsd: 15,
    payoutSpeed: 'days',
    giftCards: ['Amazon', 'Walmart', 'Target', 'PayPal'],
    regions: ['US'],
    inviteOnly: false,
    mobileOnly: false,
    notes:
      'Balances shown in real dollars rather than points, which makes the low rates impossible to hide from. The $15 threshold is the highest here — a long way to walk before you see anything.',
  },
  {
    id: 'mypoints',
    name: 'MyPoints',
    kind: 'gpt-router',
    url: 'https://www.mypoints.com/',
    payoutUnit: 'points',
    unitsPerDollar: 160,
    typicalUnitsPerSurvey: 100,
    typicalMinutes: 15,
    screenOutRate: 0.55,
    screenerMinutes: 4,
    typicalSurveysPerWeek: 12,
    minCashoutUsd: 3,
    payoutSpeed: 'days',
    giftCards: ['Amazon', 'Walmart', 'Target', 'Home Depot'],
    regions: ['US', 'CA'],
    inviteOnly: false,
    mobileOnly: false,
    notes:
      'Same operator as Swagbucks. Surveys are mediocre; the value is the shopping portal, which stacks with card rewards on purchases you were making anyway.',
  },
  {
    id: 'freecash',
    name: 'Freecash',
    kind: 'gpt-router',
    url: 'https://freecash.com/',
    payoutUnit: 'points',
    unitsPerDollar: 1000,
    typicalUnitsPerSurvey: 700,
    typicalMinutes: 15,
    screenOutRate: 0.5,
    screenerMinutes: 4,
    typicalSurveysPerWeek: 20,
    minCashoutUsd: 5,
    payoutSpeed: 'instant',
    giftCards: ['Amazon', 'Visa', 'Steam', 'PayPal'],
    regions: ['US', 'GB', 'CA', 'WW'],
    inviteOnly: false,
    mobileOnly: false,
    notes:
      'Weighted toward game and app offers rather than surveys. The headline offers pay well but expect days of play or in-app spending — read the completion terms before starting, because partial progress pays nothing.',
  },

  // ------------------------------------------------------- classic panels
  {
    id: 'yougov',
    name: 'YouGov',
    kind: 'survey-panel',
    url: 'https://today.yougov.com/',
    payoutUnit: 'points',
    unitsPerDollar: 100,
    typicalUnitsPerSurvey: 150,
    typicalMinutes: 10,
    // Well-targeted from a detailed profile, so disqualifications are uncommon.
    screenOutRate: 0.2,
    screenerMinutes: 2,
    typicalSurveysPerWeek: 5,
    minCashoutUsd: 50,
    payoutSpeed: 'weeks',
    giftCards: ['Amazon', 'Visa'],
    regions: ['US', 'GB', 'CA', 'AU', 'DE', 'FR'],
    inviteOnly: false,
    mobileOnly: false,
    notes:
      'Short, genuinely interesting political and consumer polling with a low screen-out rate. The problem is the $50 threshold, which takes most people the better part of a year — treat it as a slow background accumulator, not income.',
  },
  {
    id: 'ipsos-isay',
    name: 'Ipsos i-Say',
    kind: 'survey-panel',
    url: 'https://www.ipsos-isay.com/',
    payoutUnit: 'points',
    unitsPerDollar: 100,
    typicalUnitsPerSurvey: 75,
    typicalMinutes: 15,
    screenOutRate: 0.5,
    screenerMinutes: 4,
    typicalSurveysPerWeek: 8,
    minCashoutUsd: 5,
    payoutSpeed: 'days',
    giftCards: ['Amazon', 'Visa', 'PayPal'],
    regions: ['US', 'GB', 'CA', 'AU'],
    inviteOnly: false,
    mobileOnly: false,
    notes:
      'Run by one of the large market research firms, so the panel is stable and payouts are dependable. Rates are unremarkable; the poll-a-day habit is what makes it add up.',
  },
  {
    id: 'toluna',
    name: 'Toluna',
    kind: 'survey-panel',
    url: 'https://www.toluna.com/',
    payoutUnit: 'points',
    unitsPerDollar: 3000,
    typicalUnitsPerSurvey: 4000,
    typicalMinutes: 18,
    screenOutRate: 0.6,
    screenerMinutes: 5,
    typicalSurveysPerWeek: 10,
    minCashoutUsd: 10,
    payoutSpeed: 'weeks',
    giftCards: ['Amazon', 'Visa', 'PayPal'],
    regions: ['US', 'GB', 'CA', 'AU', 'WW'],
    inviteOnly: false,
    mobileOnly: false,
    notes:
      'Large point numbers that convert poorly — the scale is designed to feel generous. High screen-out rate and slow fulfilment; useful mainly for its product-testing invitations, which are worth more than the surveys.',
  },
  {
    id: 'lifepoints',
    name: 'LifePoints',
    kind: 'survey-panel',
    url: 'https://www.lifepointspanel.com/',
    payoutUnit: 'points',
    unitsPerDollar: 110,
    typicalUnitsPerSurvey: 100,
    typicalMinutes: 15,
    screenOutRate: 0.55,
    screenerMinutes: 4,
    typicalSurveysPerWeek: 10,
    minCashoutUsd: 5,
    payoutSpeed: 'days',
    giftCards: ['Amazon', 'Visa', 'PayPal'],
    regions: ['US', 'GB', 'CA', 'AU', 'WW'],
    inviteOnly: false,
    mobileOnly: false,
    notes:
      'Broad international coverage, which makes it one of the few worth joining outside the US and UK. Rates are ordinary and the survey invitations arrive by email rather than appearing in a dashboard.',
  },

  // --------------------------------------------------------- micro-payouts
  {
    id: 'qmee',
    name: 'Qmee',
    kind: 'survey-panel',
    url: 'https://www.qmee.com/',
    payoutUnit: 'usd',
    unitsPerDollar: 1,
    typicalUnitsPerSurvey: 0.9,
    typicalMinutes: 10,
    screenOutRate: 0.55,
    screenerMinutes: 3,
    typicalSurveysPerWeek: 8,
    // The distinguishing feature: nothing is withheld behind a threshold.
    minCashoutUsd: 0,
    payoutSpeed: 'instant',
    giftCards: ['PayPal', 'Cash'],
    regions: ['US', 'GB', 'CA', 'AU'],
    inviteOnly: false,
    mobileOnly: false,
    notes:
      'No minimum cash-out at all — withdraw any balance instantly. Payouts per survey are small, but nothing is ever stranded, which removes the main way these platforms quietly keep your earnings.',
  },
  {
    id: 'attapoll',
    name: 'AttaPoll',
    kind: 'survey-panel',
    url: 'https://attapoll.app/',
    payoutUnit: 'usd',
    unitsPerDollar: 1,
    typicalUnitsPerSurvey: 0.6,
    typicalMinutes: 8,
    screenOutRate: 0.5,
    screenerMinutes: 3,
    typicalSurveysPerWeek: 15,
    minCashoutUsd: 3,
    payoutSpeed: 'days',
    giftCards: ['PayPal', 'Amazon'],
    regions: ['US', 'GB', 'CA', 'AU', 'WW'],
    inviteOnly: false,
    mobileOnly: true,
    notes:
      'Phone-only, with short surveys that fit into gaps in the day. Rates are modest but the time commitment per survey is genuinely small, which suits queueing and commuting.',
  },
  {
    id: 'google-opinion-rewards',
    name: 'Google Opinion Rewards',
    kind: 'survey-panel',
    url: 'https://play.google.com/store/apps/details?id=com.google.android.apps.paidtasks',
    payoutUnit: 'usd',
    unitsPerDollar: 1,
    typicalUnitsPerSurvey: 0.35,
    typicalMinutes: 1,
    // Questions are triggered by places you actually visited, so you qualify.
    screenOutRate: 0.02,
    screenerMinutes: 0.2,
    typicalSurveysPerWeek: 2.5,
    minCashoutUsd: 0,
    payoutSpeed: 'instant',
    giftCards: ['Google Play'],
    regions: ['US', 'GB', 'CA', 'AU', 'IN'],
    inviteOnly: false,
    mobileOnly: true,
    notes:
      'By far the best rate per minute here, because the surveys are seconds long and you are never screened out. The catch is volume: you cannot request more, and Android pays only in Play credit, though iOS pays cash.',
  },

  // -------------------------------------------------------------- microtask
  {
    id: 'mturk',
    name: 'Amazon Mechanical Turk',
    kind: 'microtask',
    url: 'https://www.mturk.com/',
    payoutUnit: 'usd',
    unitsPerDollar: 1,
    typicalUnitsPerSurvey: 0.6,
    typicalMinutes: 5,
    // You choose your tasks, so there is no screener to fail.
    screenOutRate: 0.05,
    screenerMinutes: 1,
    typicalSurveysPerWeek: 120,
    minCashoutUsd: 1,
    payoutSpeed: 'days',
    giftCards: ['Amazon', 'Cash'],
    regions: ['US', 'WW'],
    inviteOnly: false,
    mobileOnly: false,
    notes:
      'Piecework rather than surveys, and the only platform here where skill compounds — qualifications and a good approval rating unlock far better-paying batches. Rough for the first week, respectable after that. Use a task-finder script and avoid unqualified requesters.',
  },
  {
    id: 'clickworker',
    name: 'Clickworker',
    kind: 'microtask',
    url: 'https://www.clickworker.com/',
    payoutUnit: 'usd',
    unitsPerDollar: 1,
    typicalUnitsPerSurvey: 1.2,
    typicalMinutes: 10,
    screenOutRate: 0.1,
    screenerMinutes: 2,
    typicalSurveysPerWeek: 20,
    minCashoutUsd: 5,
    payoutSpeed: 'weeks',
    giftCards: ['PayPal', 'Cash'],
    regions: ['US', 'GB', 'CA', 'AU', 'EU', 'WW'],
    inviteOnly: false,
    mobileOnly: false,
    notes:
      'Text authoring, categorisation and data work, gated behind qualification assessments you take once. Work availability is uneven, so treat it as something to check rather than rely on.',
  },

  // ------------------------------------------------------------- discovery
  {
    id: 'reddit-beermoney',
    name: 'r/beermoney',
    kind: 'gpt-router',
    url: 'https://www.reddit.com/r/beermoney/',
    discoveryUrls: ['https://www.reddit.com/r/beermoney/new.json?limit=75'],
    parser: 'reddit-json',
    payoutUnit: 'usd',
    unitsPerDollar: 1,
    typicalUnitsPerSurvey: 0,
    typicalMinutes: 0,
    screenOutRate: 0,
    screenerMinutes: 0,
    typicalSurveysPerWeek: 0,
    minCashoutUsd: 0,
    payoutSpeed: 'instant',
    giftCards: [],
    regions: ['WW'],
    inviteOnly: false,
    mobileOnly: false,
    notes:
      'Not a platform — a discovery feed. Where new panels surface first, along with the reports of which ones have stopped paying. Assume every link is a referral link.',
  },
  {
    id: 'reddit-workonline',
    name: 'r/WorkOnline',
    kind: 'gpt-router',
    url: 'https://www.reddit.com/r/WorkOnline/',
    discoveryUrls: ['https://www.reddit.com/r/WorkOnline/new.json?limit=75'],
    parser: 'reddit-json',
    payoutUnit: 'usd',
    unitsPerDollar: 1,
    typicalUnitsPerSurvey: 0,
    typicalMinutes: 0,
    screenOutRate: 0,
    screenerMinutes: 0,
    typicalSurveysPerWeek: 0,
    minCashoutUsd: 0,
    payoutSpeed: 'instant',
    giftCards: [],
    regions: ['WW'],
    inviteOnly: false,
    mobileOnly: false,
    notes:
      'Discovery feed leaning toward higher-paying remote work and research studies rather than survey grinding.',
  },
]

/** Feeds are crawled for open studies; they are not platforms you earn on. */
export function isDiscoveryFeed(panel: SurveyPanel): boolean {
  return panel.typicalUnitsPerSurvey === 0 && (panel.discoveryUrls?.length ?? 0) > 0
}

export function getPanel(id: string): SurveyPanel | undefined {
  return PANELS.find((panel) => panel.id === id)
}
